# Generated by Django 5.0 on 2024-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200)),
                ('Contact', models.IntegerField()),
            ],
            options={
                'db_table': 'myapi',
            },
        ),
    ]
