# Generated by Django 5.0 on 2024-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(default='noida', max_length=150),
            preserve_default=False,
        ),
    ]
